version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch_1
    environment:
      - node.name=elasticsearch_1
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  server:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.server
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    env_file:
      - .env
    environment:
      CLOUDAMQP_URL: amqp://rabbitmq
      REDIS_URL: redis://redis
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    command: npm run watch-dev
    ports:
      - "5000:5000"
    # NOTE: https://medium.com/@semur.nabiev/how-to-make-docker-compose-volumes-ignore-the-node-modules-directory-99f9ec224561
    volumes:
      # Bind local sources to remote volume, excluding node_modules. This is especially important
      # when developing on Mac, but are running Linux in Docker (obviously).
      - ./:/src
      - /src/node_modules
    links:
      - postgres
      - mongodb
      - rabbitmq
      - redis
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  data01:
    driver: local
