version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch_1
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  mongodb:
    image: mongo:4.2.10
    ports:
      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_DATABASE: diffme
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6-alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - redis_data:/var/lib/redis

volumes:
  mongodb_data:
  redis_data:
  data01:
    driver: local
